DROP DATABASE IF EXISTS car_sharing;

CREATE DATABASE IF NOT EXISTS car_sharing;

USE car_sharing ;

CREATE TABLE IF NOT EXISTS `currency` (
    `CURRENCY_ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) NOT NULL,
    PRIMARY KEY(`CURRENCY_ID`)
) ;

CREATE TABLE IF NOT EXISTS `pricing` (
    `PRICING_ID` INT NOT NULL AUTO_INCREMENT,
    `CURRENCY_ID` INT NOT NULL,
    `COST_PER_MIN` DECIMAL NOT NULL,
    `COST_PER_KM` DECIMAL NOT NULL,
    `FIXED_COST` DECIMAL NOT NULL,
    PRIMARY KEY (`PRICING_ID`),
    FOREIGN KEY (`CURRENCY_ID`) REFERENCES currency (`CURRENCY_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `client` (
  `CLIENT_ID` INT AUTO_INCREMENT,
  `FIRST_NAME` varchar(15) NOT NULL,
  `LAST_NAME` VARCHAR(15) NOT NULL, 
  `PHONE_NUMBER` INT NOT NULL, 
  `EMAIL` varchar(30) NOT NULL,
  `ZIP_CODE` varchar(10) NOT NULL,
  `ADDRESS` varchar(40) NOT NULL,
  `JOIN_DATE` TIMESTAMP,
  `PRICING_ID` INT NOT NULL,
  `CARD_NUMBER` BIGINT NOT NULL,
  `LICENSE_NUMBER` varchar(10) NOT NULL,
  PRIMARY KEY (`CLIENT_ID`),
  FOREIGN KEY (`PRICING_ID`) REFERENCES pricing (`PRICING_ID`)
) ;

CREATE TABLE IF NOT EXISTS `model` (
    `MODEL_ID` INT NOT NULL AUTO_INCREMENT,
    `BRAND` varchar(20) NOT NULL, 
    `MODEL_NAME` VARCHAR(20) NOT NULL,
    PRIMARY KEY(`MODEL_ID`)
) ;

CREATE TABLE IF NOT EXISTS `car` (
    `CAR_ID` INT NOT NULL AUTO_INCREMENT,
    `MODEL_ID` INT NOT NULL, 
    `PLATE_NUM` varchar(7) NOT NULL,
    `KM_TOT` INT NOT NULL,
    PRIMARY KEY(`CAR_ID`),
    FOREIGN KEY (`MODEL_ID`) REFERENCES model (`MODEL_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `country` (
    `COUNTRY_ID` VARCHAR(2) NOT NULL,
    `NAME` varchar(25) NOT NULL,
    `CURRENCY_ID` INT NOT NULL,
    PRIMARY KEY (`COUNTRY_ID`),
    FOREIGN KEY (`CURRENCY_ID`) REFERENCES currency (`CURRENCY_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `city` (
    `CITY_ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` varchar(25) NOT NULL,
    `COUNTRY_ID` VARCHAR(2) NOT NULL,
    PRIMARY KEY (`CITY_ID`),
    FOREIGN KEY (`COUNTRY_ID`) REFERENCES country (`COUNTRY_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `charging_station` (
    `STATION_ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` varchar(25) NOT NULL,
    `CITY_ID` INT NOT NULL,
    PRIMARY KEY (`STATION_ID`),
    FOREIGN KEY (`CITY_ID`) REFERENCES city (`CITY_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `charging_port` (
    `PORT_ID` INT NOT NULL AUTO_INCREMENT,
    `STATION_ID` INT NOT NULL,
    `PORT_NUMBER` TINYINT NOT NULL,
    PRIMARY KEY (`PORT_ID`),
    FOREIGN KEY (`STATION_ID`) REFERENCES charging_station (`STATION_ID`) 
) ;

CREATE TABLE IF NOT EXISTS `ride` (
    `START_DATE` TIMESTAMP NOT NULL,
    `END_DATE` TIMESTAMP NOT NULL,
    `CAR_ID` INT NOT NULL,
    `CLIENT_ID` INT NOT NULL,
    `KM` INT NOT NULL,
    `PORT_START` INT NOT NULL,
    `PORT_END` INT NOT NULL,
    PRIMARY KEY (`START_DATE`,`CLIENT_ID`, `CAR_ID`),
    FOREIGN KEY (`PORT_START`) REFERENCES charging_port (`PORT_ID`),
    FOREIGN KEY (`PORT_END`) REFERENCES charging_port (`PORT_ID`),
    FOREIGN KEY (`CLIENT_ID`) REFERENCES client (`CLIENT_ID`), 
    FOREIGN KEY (`CAR_ID`) REFERENCES car (`CAR_ID`)
) ;

CREATE TABLE IF NOT EXISTS `mischance` (
    `MISCHANCE_ID` INT NOT NULL,
    `DESCRIPTION` varchar(25) NOT NULL,
    PRIMARY KEY (`MISCHANCE_ID`)
) ;

CREATE TABLE IF NOT EXISTS `accidents` (
    `START_DATE` TIMESTAMP NOT NULL,
    `CAR_ID` INT NOT NULL,
    `CLIENT_ID` INT NOT NULL,
    `MISCHANCE_ID` INT NOT NULL,
    PRIMARY KEY (`MISCHANCE_ID`, `START_DATE`, `CAR_ID`, `CLIENT_ID`),
    FOREIGN KEY (`START_DATE`) REFERENCES ride (`START_DATE`), 
    FOREIGN KEY (`CAR_ID`) REFERENCES ride (`CAR_ID`),
    FOREIGN KEY (`CLIENT_ID`) REFERENCES ride (`CLIENT_ID`),
    FOREIGN KEY (`MISCHANCE_ID`) REFERENCES mischance (`MISCHANCE_ID`)
) ;

CREATE TABLE IF NOT EXISTS `invoice` (
    `START_DATE` TIMESTAMP NOT NULL,
    `CAR_ID` INT NOT NULL,
    `CLIENT_ID` INT NOT NULL,
    `PRICING_ID` INT NOT NULL,
    PRIMARY KEY (`PRICING_ID`, `START_DATE`, `CAR_ID`, `CLIENT_ID`),
    FOREIGN KEY (`START_DATE`) REFERENCES ride (`START_DATE`), 
    FOREIGN KEY (`CAR_ID`) REFERENCES ride (`CAR_ID`),
    FOREIGN KEY (`CLIENT_ID`) REFERENCES ride (`CLIENT_ID`)
) ;

